version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    # ports:
    #   - "3000:3000"
    volumes:
      - ./app/:/usr/src/app/
      - node_modules:/usr/src/app/node_modules
      - /usr/src/app/.next
    env_file:
      - ./.env.dev
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - api
      - app

volumes:
  postgres_data:
  static_volume:
  node_modules: